# URL of the source GitLab (from which to migrate)
source_gitlab_url: "https://source.gitlab.example.com"

# URL of the target GitLab (to which to migrate).
# If empty — source_gitlab_url will be used
target_gitlab_url: "https://target.gitlab.example.com"

# API token for the source GitLab
source_access_token: "YOUR_SOURCE_PRIVATE_TOKEN"

# API token for the target GitLab.
# If empty — source_access_token will be used
target_access_token: "YOUR_TARGET_PRIVATE_TOKEN"

# Full path of the source group (source namespace)
# Specified in the group's URL-path format
source_group: "main-group-name/subgroup-name"

# Full path of the target group (target namespace)
# Specified in the group's URL-path format
target_group: "main-group-name/subgroup-name"
